# Generated by Django 3.2.8 on 2021-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain_DB',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.FloatField()),
                ('cur_tran', models.CharField(max_length=250)),
                ('proof', models.IntegerField()),
                ('prev_hash', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='trdb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=250)),
                ('recipient', models.CharField(max_length=250)),
                ('amt', models.IntegerField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coins_received', models.CharField(max_length=15)),
                ('coins_sent', models.CharField(max_length=15)),
            ],
        ),
    ]
