# Generated by Django 3.2.8 on 2021-10-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coins_received',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coins_sent',
        ),
        migrations.AlterField(
            model_name='chain_db',
            name='cur_tran',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trdb',
            name='recipient',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='trdb',
            name='sender',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
