# Generated by Django 3.2.8 on 2021-10-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0002_auto_20211025_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trdb',
            name='recipient',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='trdb',
            name='sender',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
